// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/todovendng/LandingPage.tsx": () => import("../components/mockups/todovendng/LandingPage.tsx"),
  "./components/mockups/todovendng/MadeByBadge.tsx": () => import("../components/mockups/todovendng/MadeByBadge.tsx")
};
